"""
Database Seeder Script
Populate database with dummy data for testing purposes.
"""
import sys
import os
import asyncio
import random
from datetime import datetime, timedelta

# Add parent directory to path to allow imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from api.app.utils.config import settings
from api.app.models.database import DbConnection, DatabaseType
from api.app.services.database.factory import DatabaseFactory
from api.app.services.database.base import BaseDatabaseConnector


async def seed_database():
    """Seed the database with dummy data"""
    print(f"🚀 Starting database seeder...")
    
    # Check if database config is present
    if not settings.DB_HOST and not settings.DB_NAME:
        print("❌ Error: Database configuration missing in .env")
        print("Please configure DB_HOST, DB_USER, DB_PASS, DB_NAME in .env file first.")
        return

    print(f"🔌 Connecting to {settings.DB_TYPE} database at {settings.DB_HOST}...")
    
    # Create connection object from settings
    connection = DbConnection(
        host=settings.DB_HOST,
        port=settings.DB_PORT,
        username=settings.DB_USER,
        password=settings.DB_PASS,
        database=settings.DB_NAME,
        type=settings.DB_TYPE,
        connection_string=settings.DB_URI
    )
    
    try:
        # Get connector
        connector = DatabaseFactory.get_connector(connection)
        
        # Connect
        if not await connector.connect():
            print("❌ Failed to connect to database.")
            return

        print("✅ Connected successfully!")
        
        # Determine schema DDL based on database type
        # Ideally this should be more robust, but for seeder we use simple standard SQL
        # Adjusting types for different DBs
        serial_type = "SERIAL PRIMARY KEY"
        datetime_type = "TIMESTAMP"
        
        if settings.DB_TYPE == DatabaseType.MYSQL:
            serial_type = "INT AUTO_INCREMENT PRIMARY KEY"
            datetime_type = "DATETIME"
        elif settings.DB_TYPE == DatabaseType.SQLSERVER:
            serial_type = "INT IDENTITY(1,1) PRIMARY KEY"
        elif settings.DB_TYPE == DatabaseType.ORACLE:
            serial_type = "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY"
            datetime_type = "TIMESTAMP"
        elif settings.DB_TYPE == DatabaseType.SQLITE:
            serial_type = "INTEGER PRIMARY KEY AUTOINCREMENT"
            
        
        # Create Tables
        print("\n🛠️ Creating tables...")
        
        # Products Table
        create_products = f"""
        CREATE TABLE IF NOT EXISTS products (
            id {serial_type},
            name VARCHAR(100) NOT NULL,
            category VARCHAR(50),
            price DECIMAL(10, 2),
            stock INT DEFAULT 0,
            created_at {datetime_type} DEFAULT CURRENT_TIMESTAMP
        )
        """
        
        # Sales Table
        create_sales = f"""
        CREATE TABLE IF NOT EXISTS sales (
            id {serial_type},
            product_id INT,
            quantity INT,
            total_price DECIMAL(10, 2),
            sale_date {datetime_type} DEFAULT CURRENT_TIMESTAMP,
            status VARCHAR(20)
        )
        """
        
        # Execute create table queries
        # Note: generic execute_query is generic and might return results.
        # This part depends on how specific connector implements execute_query.
        # Most of our connectors use cursor.execute() which handles DDL.
        
        # We need to bypass _validate_read_only check for seeding.
        # Ideally we should have a specific method for DDL execution, but efficient way for this script:
        # We access the internal cursor/connection directly or modify the connector to allow writes.
        # BUT, our BaseDatabaseConnector enforces read-only in execute_query.
        
        # WORKAROUND: We will directly use the internal connection object if possible, 
        # or we rely on the fact that this script is local and we can just use the driver directly?
        # Better: let's stick to using the connector but since it IS read-only, we might fail.
        
        # Looking at base.py, _validate_read_only raises ValueError if it detects write operations.
        # So we cannot use connector.execute_query().
        
        # We will access the underlying connection directly for this seeder script.
        # This breaks encapsulation but creates a pragmatic solution for a dev tool.
        
        if settings.DB_TYPE == DatabaseType.POSTGRESQL:
            import psycopg2
            conn = connector._connection
            cursor = conn.cursor()
            
            # Note: For Supabase, this works with standard PostgreSQL connection
            cursor.execute(create_products)
            cursor.execute(create_sales)
            conn.commit()
            
        elif settings.DB_TYPE == DatabaseType.MYSQL:
            conn = connector._connection
            cursor = conn.cursor()
            cursor.execute(create_products)
            cursor.execute(create_sales)
            conn.commit()
            
        elif settings.DB_TYPE == DatabaseType.SQLITE:
            conn = connector._connection
            cursor = conn.cursor()
            cursor.execute(create_products)
            cursor.execute(create_sales)
            conn.commit()

        elif settings.DB_TYPE == DatabaseType.MONGODB:
            # MongoDB doesn't "create tables", but we ensure collections exist 
            # by inserting data.
            print("   MongoDB detected: Skipping explicit table creation.")
            pass
            
        # For other DBs add support as needed
        else:
            print(f"⚠️ Seeding not fully implemented for {settings.DB_TYPE} in this script yet.")
            if settings.DB_TYPE == "Firebase":
                print("Firebase connector is not yet implemented. Please implement the connector first.")
            await connector.disconnect()
            return

        print("✅ Tables created.")
        
        # Insert Dummy Data
        print("\n🌱 Inserting dummy data...")
        
        products = [
            ("Laptop Pro X", "Electronics", 1200.00, 50),
            ("Smartphone Z", "Electronics", 800.00, 100),
            ("Coffee Maker", "Home", 150.00, 30),
            ("Desk Chair", "Furniture", 250.00, 20),
            ("Running Shoes", "Apparel", 90.00, 200),
            ("4K Monitor", "Electronics", 400.00, 40),
            ("Mechanical Keyboard", "Electronics", 120.00, 60),
            ("Thermos Bottle", "Home", 25.00, 150),
        ]
        
        conn = connector._connection
        product_ids = []
        
        if settings.DB_TYPE == DatabaseType.POSTGRESQL:
            cursor = conn.cursor()
            for p in products:
                cursor.execute(
                    "INSERT INTO products (name, category, price, stock) VALUES (%s, %s, %s, %s) RETURNING id",
                    p
                )
                product_id = cursor.fetchone()[0]
                product_ids.append(product_id)
            conn.commit()

        elif settings.DB_TYPE == DatabaseType.MYSQL:
            cursor = conn.cursor()
            for p in products:
                cursor.execute(
                    "INSERT INTO products (name, category, price, stock) VALUES (%s, %s, %s, %s)",
                    p
                )
                product_ids.append(cursor.lastrowid)
            conn.commit()

        elif settings.DB_TYPE == DatabaseType.SQLITE:
            cursor = conn.cursor()
            for p in products:
                cursor.execute(
                    "INSERT INTO products (name, category, price, stock) VALUES (?, ?, ?, ?)",
                    p
                )
                product_ids.append(cursor.lastrowid)
            conn.commit()

        elif settings.DB_TYPE == DatabaseType.MONGODB:
            db = connector._db
            # Preparing mongo docs
            mongo_products = [
                {"name": p[0], "category": p[1], "price": p[2], "stock": p[3], "created_at": datetime.now()}
                for p in products
            ]
            result = db.products.insert_many(mongo_products)
            product_ids = result.inserted_ids

        # print(f"   Inserted {len(product_ids)} products.")
        
        # Generate Sales
        sales_count = 50
        print(f"   Generating {sales_count} sales records...")
        
        if settings.DB_TYPE == DatabaseType.MONGODB:
            db = connector._db
            mongo_sales = []
            for _ in range(sales_count):
                p_id = random.choice(product_ids)
                qty = random.randint(1, 5)
                total = qty * 100.00
                status = random.choice(["completed", "pending", "cancelled", "returned"])
                sale_date = datetime.now() - timedelta(days=random.randint(0, 30))
                mongo_sales.append({
                    "product_id": p_id,
                    "quantity": qty,
                    "total_price": total,
                    "status": status,
                    "sale_date": sale_date
                })
            db.sales.insert_many(mongo_sales)
        else:
            cursor = conn.cursor()
            for _ in range(sales_count):
                p_id = random.choice(product_ids)
                qty = random.randint(1, 5)
                total = qty * 100.00 
                status = random.choice(["completed", "pending", "cancelled", "returned"])
                sale_date = datetime.now() - timedelta(days=random.randint(0, 30))
                
                if settings.DB_TYPE == DatabaseType.POSTGRESQL or settings.DB_TYPE == DatabaseType.MYSQL:
                    cursor.execute(
                        "INSERT INTO sales (product_id, quantity, total_price, status, sale_date) VALUES (%s, %s, %s, %s, %s)",
                        (p_id, qty, total, status, sale_date)
                    )
                elif settings.DB_TYPE == DatabaseType.SQLITE:
                    cursor.execute(
                        "INSERT INTO sales (product_id, quantity, total_price, status, sale_date) VALUES (?, ?, ?, ?, ?)",
                        (p_id, qty, total, status, sale_date)
                    )
            conn.commit()
        print("✅ Data inserted successfully!")
        
        await connector.disconnect()
        
    except Exception as e:
        print(f"\n❌ Error seeding database: {str(e)}")
        import traceback
        traceback.print_exc()

if __name__ == "__main__":
    asyncio.run(seed_database())
